[build-system]
requires = ["setuptools>=42.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyalgos"
version = "0.1.0"
authors = [
    {name = "Bibin"}
]

[tool.pytest.ini_options]
pythonpath = [
    "src"
]
testpaths = ["tests"]